[[news]]
date = "2022年12月"
content = "国家奖学金"
icon = "🏆"
highlight = true

[[news]]
date = "2023年12月"
content = "黑龙江省三好学生"

[[news]]
date = "2024年04月"
content = "黑龙江省优秀毕业生"

[[news]]
date = "2024年"
content = "上海交通大学医学院一等奖学金"

[[news]]
date = "2025年"
content = "上海交通大学医学院一等奖学金"
